import getConfig from "next/config";

export default function Head() {

  return (
    <>
      <title>{process.env.NEXT_PUBLIC_SITENAME}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
    </>
  );
}
